## test playbook to show the structure and also to test the new roles being created.
#
#


  - name: Configure Clear test machines
    hosts: test
    become: true
    roles:
      - bphipps_account
      - ntp
      - jenkins

