
    - name: install sysadmin-basic bundle
      swupd:
        state: present
        name: sysadmin-basic
      when: ansible_os_family == "ClearLinux"

    - name: set timezone
      shell: timedatectl set-timezone America/Los_Angeles

    - name: copy timesyncd.conf into place
      template: src=templates/timesyncd.conf dest=/etc/systemd/timesyncd.conf

    - name: set ntp true
      shell: timedatectl set-ntp true

    - name: restart timesyncd
      shell: systemctl restart systemd-timesyncd

