" Basic .vimrc
" Created by Karl Vietmeier

" We use it in CLI - just need basic vi mode
set compatible

" Turn on syntax highlighting
syntax on

" Show line numbers
"set number

" Show file stats
set ruler

" Status bar
set laststatus=2

" Last line
set showmode
set showcmd

" Whitespace
"set wrap
"set textwidth=72
"set formatoptions=tcqrn1
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab


" Color scheme (terminal)
"set t_Co=256
"set background=dark
"let g:solarized_termcolors=256
"let g:solarized_termtrans=1
" put https://raw.github.com/altercation/vim-colors-solarized/master/colors/solarized.vim
" in ~/.vim/colors/ and uncomment:
" colorscheme solarized
